### ISSUE TITLE
YNAB exporter stuck on "Starting"

### ISSUE THREAD

**Issue by Nitaym** [brafdlog/caspion#462] opened 2023-03-15 18:34 UTC
Pretty much the title, I only see a spinner and nothing else. 

(Let me know how to add more information - Is there a way to find more information without opening a dev env?)

Also, the automatic fields are missing information - Where can I find it? I'll add it to the bug:

        ## System Info
        
         - Source Version: `SOURCE_COMMIT_SHORT`
         - OS: `browserjavascript`
         - OS Version: `5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) caspion/1.11.4 Chrome/98.0.4758.141 Electron/17.4.11 Safari/537.36`

**Comment by baruchiro** [comment] 2023-03-19 06:30
@brafdlog

**Comment by Nitaym** [comment] 2023-09-03 12:00
@baruchiro @brafdlog can I offer any assistance with this? This is a real problem for me

**Comment by baruchiro** [comment] 2023-09-03 16:30
@Nitaym yes, we really need help here

**Comment by brafdlog** [comment] 2023-09-03 19:08
Hey, sorry for the latency.
What do you mean when you say the automatic fields are missing information?
Do you see any errors in the log?

**Comment by baruchiro** [comment] 2023-12-20 01:14
Hi, is it still happening?

**Comment by skoant** [comment] 2024-01-09 17:04
I have the same issue.
When configring YNAB, budget id fetched successfully but the "Ynab account id" is empty.

**Comment by brafdlog** [comment] 2024-01-09 20:11
@skoant You mean that the cells in the ynab account it column don't get prepopulated?

Please open caspion, open dev tools (`Ctrl+Shift+I` for windows or `cmd+alt+I` for mac) and see in the console the logs, tell me what you see there (don't paste here any account senstivie data, you can blank that out and share the generic log)

**Comment by shaiu** [comment] 2024-09-14 18:38
@brafdlog getting the same.
Here is the console log screenshot:
<img width="544" alt="image" src="https://github.com/user-attachments/assets/3a7034b3-31f8-4155-bd59-4cd3fed235a8">

status: "INVALID_BUDGET_ID"

**Comment by brafdlog** [comment] 2024-09-14 19:42
The title of the issue is Ynab exporter stuck.
Are you stuck during the export or when changing the settings of ynab?
This error: INVALID_BUDGET_ID is sent when no categories are returned from ynab, this could indicate that the budget id is invalid.
Please go to the settings and try to choose the budget again and save, and try again.

**Comment by shaiu** [comment] 2024-09-14 22:36
@brafdlog The issues are related

The `Ynab account id` isn't being populated because of the bug I'm fixing when there is only one budget id in the list.
Because it's not being populated the YNAB exporter get stuck on "Starting"

**Comment by shaiu** [comment] 2024-10-25 05:06
@Nitaym Is this still happening with the new versions?

**Comment by shaiu** [comment] 2024-11-04 18:44
@baruchiro @brafdlog I think we can close this

**Comment by baruchiro** [comment] 2024-11-07 05:37
@shaiu I'm dreaming about a stale bot https://github.com/actions/stale 😉

**Closed by baruchiro** 2024-11-07 05:37 UTC
Labels: need logs
